version: '3'

services:
  nginx:
    container_name: l_nginx
    image: nginx:stable-alpine
    ports:
      - 8080:80
    depends_on:
      - app
      - db
    volumes:
      - ./laravel-app:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - laravel

  db:
    container_name: l_mysql_db
    image: mysql:8.0
    restart: always
    ports:
     - 33306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravel-bike
      MYSQL_ROOT_PASSWORD: toor
    networks:
      - laravel
  
  phpmyadmin:
    container_name: l_phpmyadmin
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - db
    networks:
      - laravel
    
  app:
    container_name: l_app
    build: .
    volumes:
      - ./laravel-app:/var/www/html
    ports:
      - 9000:80
    networks:
      - laravel

volumes:
  bd:
    driver: local
  app:
    driver: local

networks:
  laravel: